package hakancemgercek.harfvekelimefrekansi;


public class HarfveKelimeFrekansi extends javax.swing.JFrame {    
    /**
     * Creates new form HarfveKelimeFrekansi
     */
    public HarfveKelimeFrekansi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        kelimeSayisi_label = new javax.swing.JLabel();
        karakterSayisi_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        metin_TextArea = new javax.swing.JTextArea();
        kelimeHarfSayisiGoster_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kelime ve Harf Sayısı Bulma");

        kelimeSayisi_label.setText("Kelime sayısı: ");

        karakterSayisi_label.setText("Karakter sayısı: ");

        metin_TextArea.setColumns(20);
        metin_TextArea.setRows(5);
        jScrollPane1.setViewportView(metin_TextArea);

        kelimeHarfSayisiGoster_button.setText("Göster");
        kelimeHarfSayisiGoster_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelimeHarfSayisiGoster_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kelimeSayisi_label))
                        .addContainerGap(127, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(karakterSayisi_label)
                            .addComponent(kelimeHarfSayisiGoster_button))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(kelimeSayisi_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karakterSayisi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kelimeHarfSayisiGoster_button)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void kelimeHarfSayisiGoster_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
        String metin;
        int karakterSayisi=0;
        int kelimeSayisi=0;
        metin = metin_TextArea.getText();
        
        for(int i=0; i<metin.length(); i++){
            if(metin.charAt(i) != ' '){
                karakterSayisi++;
            }
            
        }
        
        if(metin.isEmpty()){
            kelimeSayisi_label.setText("Kelime sayısı: 0");
        }
        else{
            String[] kelime_dizi = metin.split(" ");
            for(String kelime_dizi2 : kelime_dizi){
                kelimeSayisi++;
            }
            kelimeSayisi_label.setText(String.valueOf("Kelime sayısı: "+kelimeSayisi));
        }        
        
        karakterSayisi_label.setText(String.valueOf("Karakter sayısı: "+karakterSayisi));
        
    }                                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HarfveKelimeFrekansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HarfveKelimeFrekansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HarfveKelimeFrekansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HarfveKelimeFrekansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HarfveKelimeFrekansi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel karakterSayisi_label;
    private javax.swing.JButton kelimeHarfSayisiGoster_button;
    private javax.swing.JLabel kelimeSayisi_label;
    private javax.swing.JTextArea metin_TextArea;
    // End of variables declaration                   
}
