/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hakancemgercek.siparisuygulamasi;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author hakan
 */
public class SiparisUygulamasi extends javax.swing.JFrame {
    Map<String,Integer> siparisler = new LinkedHashMap<String, Integer>();
    /**
     * Creates new form SiparisUygulamasi
     */
    public SiparisUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menu_label = new javax.swing.JLabel();
        lahmacun_checkBox = new javax.swing.JCheckBox();
        pirincPilavi_checkBox = new javax.swing.JCheckBox();
        ayran_CheckBox = new javax.swing.JCheckBox();
        sepeteEkle_button = new javax.swing.JButton();
        mercimekCorbasi_checkBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siparis");

        menu_label.setText("MENÜ");

        lahmacun_checkBox.setText("Lahmacun - 50 ₺");

        pirincPilavi_checkBox.setText("Pirinç Pilavı - 45 ₺");

        ayran_CheckBox.setText("Ayran - 20 ₺");

        sepeteEkle_button.setText("Sepete Ekle");
        sepeteEkle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepeteEkle_buttonActionPerformed(evt);
            }
        });

        mercimekCorbasi_checkBox.setText("Mercimek Çorbası - 50 ₺");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(menu_label)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sepeteEkle_button)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ayran_CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lahmacun_checkBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pirincPilavi_checkBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mercimekCorbasi_checkBox, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                        .addGap(114, 114, 114))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(menu_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lahmacun_checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mercimekCorbasi_checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pirincPilavi_checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ayran_CheckBox)
                .addGap(18, 18, 18)
                .addComponent(sepeteEkle_button)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    public void siparisGoster(){
        String mesaj="";
        int tutar=0;
        if(siparisler.isEmpty()){
            mesaj="Sipariş bulunmamaktadır!";
        }
        else{
            mesaj+="Siparişler:\n";
            for(Map.Entry<String, Integer> entry : siparisler.entrySet()){
                mesaj += entry.getKey()+"\n";
                tutar += entry.getValue();
            }
            mesaj += "Toplam tutar: "+tutar+" ₺";
        }
        JOptionPane.showMessageDialog(this, mesaj);
    }
    private void sepeteEkle_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        if(lahmacun_checkBox.isSelected()){
            siparisler.put("Lahmacun", 50);
        }
        else{
            siparisler.remove("Lahmacun");
        }
        
        if(mercimekCorbasi_checkBox.isSelected()){
            siparisler.put("Mercimek Çorbası", 50);
        }
        else{
            siparisler.remove("Mercimek Çorbası");
        }
        
        if(pirincPilavi_checkBox.isSelected()){
            siparisler.put("Pirinç Pilavı", 45);
        }
        else{
            siparisler.remove("Pirinç Pilavı");
        }
        
        if(ayran_CheckBox.isSelected()){
            siparisler.put("Ayran", 20);
        }
        else{
            siparisler.remove("Ayran");
        }
        siparisGoster();
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox ayran_CheckBox;
    private javax.swing.JCheckBox lahmacun_checkBox;
    private javax.swing.JLabel menu_label;
    private javax.swing.JCheckBox mercimekCorbasi_checkBox;
    private javax.swing.JCheckBox pirincPilavi_checkBox;
    private javax.swing.JButton sepeteEkle_button;
    // End of variables declaration                   
}
